app/settings/forms.py
from wtforms import (
    StringField, ValidationError, SubmitField,
    PasswordField, TextAreaField
)

from wtforms.validators import Required, Length, Email, EqualTo, URL, Optional

from flask.ext.wtf import Form

from app.models import User

from flask.ext.babel import gettext
_ = gettext


class EditProfileForm(Form):
    name = StringField(_('Tên hiển thị'), validators=[Length(0, 64)])
    location = StringField(_('Vị trí'), validators=[Length(0, 64)])
    url = StringField(_('URL'), validators=[Optional(), URL(), Length(0, 64)])
    submit = SubmitField(_('Lưu lại'))


class ChangePasswordForm(Form):
    old_password = PasswordField(_('Mật khẩu hiện tại'), validators=[Required()])
    password = PasswordField(_('Mật khẩu mới'), validators=[
        Length(6, 32, message=_('Mật khẩu phải từ 6 đến 32 ký tự')),
        Required(), EqualTo('password2', message=_('Chưa khớp mật khẩu'))])
    password2 = PasswordField(_('Xác nhận mật khẩu mới'), validators=[Required()])
    submit = SubmitField(_('Đổi mật khẩu'))


class ChangeEmailForm(Form):
    email = StringField(_('Email mới'), validators=[Required(), Length(1, 64),
                                                 Email()])
    password = PasswordField(_('Mật khẩu'), validators=[Required()])
    submit = SubmitField(_('Đổi email'))

    def validate_email(self, field):
        if User.query.filter_by(email=field.data).first():
            raise ValidationError(_('Email này đã được sử dụng'))


class ContactForm(Form):
    subject = StringField(_('Chủ đề'), validators=[Required(), Length(1, 64)])
    body = TextAreaField(_('Nội dung'), validators=[Required()])
    submit = SubmitField(_('Gửi đi'))

app/settings/__init__.py
from flask import Blueprint

settings = Blueprint('settings', __name__)

from app.settings import views

app/settings/views.py
from flask import render_template, redirect, url_for, flash, current_app

from flask.ext.login import login_required, current_user

from app import db

from app.settings import settings
from app.settings.forms import (
    EditProfileForm, ChangePasswordForm, ChangeEmailForm,
    ContactForm
)

from app.email import send_email

from flask.ext.babel import gettext
_ = gettext


@settings.route('/')
@login_required
def index():
    return redirect(url_for('.edit_profile'))

class Tab():
    def __init__(self, number, text):
        self.number = number
        self.text = text

@settings.route('/edit-profile', methods=['GET', 'POST'])
@login_required
def edit_profile():
    form = EditProfileForm()
    if form.validate_on_submit() and current_user.enabled:
        current_user.name = form.name.data
        current_user.location = form.location.data
        current_user.url = form.url.data
        db.session.add(current_user)
        flash(_('Hồ sơ đã được cập nhật'))
        return redirect(url_for('.edit_profile'))
    form.name.data = current_user.name
    form.location.data = current_user.location
    form.url.data = current_user.url
    selection = Tab(1, _('Chỉnh sửa hồ sơ'))
    return render_template('settings/settings.html', 
                           form=form, selection=selection)


@settings.route('/change-password', methods=['GET', 'POST'])
@login_required
def change_password():
    form = ChangePasswordForm()
    if form.validate_on_submit() and current_user.enabled:
        if current_user.verify_password(form.old_password.data):
            current_user.password = form.password.data
            db.session.add(current_user)
            flash(_('Mật khẩu của bạn đã được thay đổi'))
            return redirect(url_for('.change_password'))
        else:
            flash(_('Mật khẩu chưa đúng'))
    selection = Tab(3, _('Thay đổi mật khẩu'))
    return render_template("settings/settings.html",
                           form=form, selection=selection)


@settings.route('/change-email', methods=['GET', 'POST'])
@login_required
def change_email_request():
    form = ChangeEmailForm()
    if form.validate_on_submit() and current_user.enabled:
        if current_user.verify_password(form.password.data):
            new_email = form.email.data
            token = current_user.generate_email_change_token(new_email)
            send_email(new_email, _('Xác nhận địa chỉ email mới'),
                       'auth/email/change_email',
                       user=current_user, token=token)
            flash(_('Một email với hướng dẫn xác nhận đã được gửi đi'))
            return redirect(url_for('.change_email_request'))
        else:
            flash(_('Mật khẩu chưa đúng'))
    selection = Tab(4, _('Thay đổi email'))
    return render_template("settings/settings.html",
                           form=form, selection=selection)


@settings.route('/change-email/<token>')
@login_required
def change_email(token):
    if current_user.change_email(token):
        flash(_('Xác nhận thành công địa chỉ email mới'))
    else:
        flash(_('Yêu cầu không hợp lệ'))
    return redirect(url_for('main.index'))


@settings.route('/contact', methods=['GET', 'POST'])
@login_required
def contact():
    form = ContactForm()
    if form.validate_on_submit():
        send_email(current_app.config['MAIL_ADMIN'],
                   form.subject.data,
                   'admin/email/contact',
                   user=current_user,
                   body=form.body.data)
        flash(_('Gửi thư đi thành công, chúng tôi sẽ liên hệ lại với bạn'))
        form.subject.data = ""
        form.body.data = ""
    selection = Tab(5, _('Liên hệ'))
    return render_template("settings/settings.html",
                           form=form, selection=selection)

app/templates/settings/settings.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}{{ _('Cài đặt') }} - Việt Nôm{% endblock %}

{% block page_content %}
<div class="col-md-3">

<div class="panel panel-default">
    <div class="panel-heading">{{ _('Cài đặt') }}</div>
    <ul class="list-group">
        <a href="{{ url_for('settings.edit_profile') }}" class="list-group-item 
            {{ 'list-group-item-info' if selection.number == 1 }}">
            {{ _("Chỉnh sửa hồ sơ") }}
        </a>
        <a href="{{ url_for('settings.change_password') }}" class="list-group-item 
            {{ 'list-group-item-info' if selection.number == 3 }}" id="change-password">
            {{ _("Thay đổi mật khẩu") }}
        </a>
        <a href="{{ url_for('settings.change_email_request') }}" class="list-group-item 
            {{ 'list-group-item-info' if selection.number == 4 }}" id="change-email">
            {{ _("Thay đổi email") }}
        </a>
    </ul>
</div>
<div class="panel panel-default">
    <div class="panel-heading">{{ _('Tiện ích') }}</div>
    <ul class="list-group">
        <a href="{{ url_for('settings.contact') }}" class="list-group-item
            {{ 'list-group-item-info' if selection.number == 5 }}">
            {{ _("Yêu cầu hoặc báo lỗi") }}
        </a>
        <a href="{{ url_for('main.export_csv') }}" class="list-group-item">
            {{ _("Xuất dữ liệu (CSV)") }}
        </a>
    </ul>
</div>

</div>

<div class="col-md-7">
    <div class="panel panel-default">
        <div class="panel-heading">{{ selection.text }}</div>
        <div class="panel-body">
            <div class="col-md-6">
                {{ wtf.quick_form(form) }}
            </div>
        </div>
    </div>
    </div>
</div>
{% endblock %}