app/main/forms.py
from flask.ext.wtf import Form
from wtforms import StringField, BooleanField, SubmitField
from wtforms.validators import Length

from flask.ext.pagedown.fields import PageDownField

from flask.ext.babel import gettext
_ = gettext


class PostForm(Form):
    keyword = StringField(_('Từ khóa'), validators=[Length(0, 16)])
    story = PageDownField(_('Mẩu chuyện'), validators=[Length(0, 320)])
    shared = BooleanField(_('Chia sẻ mẩu chuyện này'))
    submit = SubmitField(_('Lưu lại'))

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from app.main import views, errors
from app.models import Permission


@main.app_context_processor
def inject_permissions():
    return dict(Permission=Permission)

app/main/views.py
from flask import (
    render_template, redirect, url_for, abort,
    flash, request, current_app,
    Response, stream_with_context
)
from flask.ext.login import login_required, current_user

from app import db, cache
from app.models import User, Permission, Post, Nom

from app.main import main
from app.decorators import teller_required
from app.main.forms import PostForm

from flask.ext.babel import gettext
_ = gettext


@main.route('/')
def index():
    return render_template('index.html')


@main.route('/nom')
def nom_index():
    page = request.args.get('page', 1, type=int)
    pagination = Nom.query.order_by(Nom.id).paginate(
        page, per_page=current_app.config['NOMS_PER_PAGE'],
        error_out=False
    )
    noms = pagination.items
    return render_template('main/nom_index.html',
                           noms=noms, pagination=pagination)


@main.route('/nom/<int:id>')
@login_required
def nom_view(id):
    nom = Nom.query.get_or_404(id)
    my_post = Post.query.filter_by(nom=nom, author=\
                                   current_user._get_current_object()).first()
    page = request.args.get('page', 1, type=int)
    pagination = Post.query.filter_by(nom=nom, shared=True).\
        order_by(Post.id).\
        paginate(
            page, per_page=current_app.config['POST_PER_PAGE'],
            error_out=False
        )
    posts = pagination.items
    return render_template('main/nom_view.html',
                           nom=nom, my_post=my_post,
                           posts=posts, pagination=pagination)


@main.route('/nom/<int:id>/edit', defaults={'ver': ''}, methods=['GET', 'POST'])
@main.route('/nom/<int:id>/edit/<int:ver>', methods=['GET', 'POST'])
@login_required
@teller_required
def edit_post(id, ver):
    if ver and ver > 1:
        abort(404)
    nom = Nom.query.get_or_404(id)
    author = current_user._get_current_object()
    post = Post.query.filter_by(nom=nom, author=author).first()
    if post is None:
        post = Post(keyword=nom.keyword, story="", nom=nom, author=author)
        db.session.add(post)

    form = PostForm()
    if form.validate_on_submit():
        if post.keyword != form.keyword.data or \
                post.story != form.story.data:
            post.keyword_backup = post.keyword
            post.keyword = form.keyword.data
            post.story_backup = post.story
            post.story = form.story.data 
            post.shared = form.shared.data
            db.session.add(post)
        elif post.shared != form.shared.data:
            post.shared = form.shared.data
            db.session.add(post)
        cache.delete_memoized(user)
        return redirect(url_for('.nom_view', id=nom.id))

    form.keyword.data = post.keyword_backup if ver else post.keyword
    form.story.data = post.story_backup if ver else post.story
    form.shared.data = post.shared

    return render_template('main/nom_edit.html',
                           nom=nom, form=form, ver=ver)


@main.route('/nom/vote/<int:id>/<vote>')
@login_required
def vote_post(id, vote):
    post = Post.query.get_or_404(id)
    if vote == 'up':
        current_user.up(post)
    elif vote == 'down':
        current_user.down(post)
    return redirect(url_for('.nom_view', id=post.nom_id))


@main.route('/nom/copy/<int:id>')
@login_required
def copy_post(id):
    from_post = Post.query.get_or_404(id)
    user = current_user._get_current_object()
    to_post = Post.query.filter_by(author=user,
                                   nom_id=from_post.nom_id).first()
    if current_user.can(Permission.TELL):
        if to_post is None:
            to_post = Post(keyword=from_post.keyword,
                           story=from_post.story,
                           nom=from_post.nom,
                           author=user)
        else:
            to_post.keyword_backup = to_post.keyword
            to_post.keyword = from_post.keyword

            to_post.story_backup = to_post.story
            to_post.story = from_post.story

        db.session.add(to_post)
        return redirect(url_for('.edit_post', id=from_post.nom_id))
    else:
        flash(_('Xin lỗi, bạn không đủ quyền để sao chép câu chuyện'))
        return redirect(url_for('.nom_view', id=from_post.nom_id))


@main.route('/export/vietnom.csv')
@login_required
def export_csv():
    def generate():
        user=current_user._get_current_object()
        for post in user.posts.all():
            nom = Nom.query.get_or_404(post.nom_id)
            csv = '"{}","{}","{}","{}"\n'.format(post.nom_id, nom.character,
                                         post.keyword, post.story)
            yield csv
    return Response(stream_with_context(generate()), mimetype='text/csv')


@main.route('/user/<username>')
@login_required
@cache.memoize(60*5)
def user(username):
    user = User.query.filter_by(username=username).first_or_404()
    page = request.args.get('page', 1, type=int)
    pagination = Post.query.filter_by(author=user,shared=True).\
        order_by(Post.nom_id).\
        paginate(
            page, per_page=current_app.config['POST_PER_PAGE'],
            error_out=False,
        )
    posts = pagination.items
    return render_template('main/user.html', user=user,
                           posts=posts, pagination=pagination)

app/templates/main/nom_edit.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}{{ _('Sửa mẩu chuyện') }} - Việt Nôm{% endblock %}

{% block page_content %}
<div class="col-md-3">
<div class="panel panel-default">
    <ul class="list-group">
        <a href="{{ url_for('main.edit_post', id=nom.id) }}" class="list-group-item 
            {{ 'list-group-item-info' if not ver }}">
            {{ _("Bản hiện hành") }}
        </a>
        <a href="{{ url_for('main.edit_post', id=nom.id, ver=1) }}" class="list-group-item 
            {{ 'list-group-item-info' if ver }}">
            {{ _("Bản sao lưu") }}
        </a>
    </ul>
</div>
</div>

<div class="col-md-7">
    <div class="page-header">
        <h1>{{ nom.character }}
            <span class="pull-right"><a href="{{ url_for('.nom_view', id=nom.id) }}">
                    <button class="btn btn-danger">{{ _('Hủy thay đổi') }}</button></a>
            </span>
        </h1>
    </div>
    <div>
        {{ wtf.quick_form(form) }}
    </div>
</div>
{% endblock %}

{% block scripts %}
{{ super() }}
{{ pagedown.include_pagedown() }}
{% endblock %}

app/templates/main/nom_index.html
{% extends "base.html" %}
{% import "_macros.html" as macros %}
{% block title %}{{ _('Những chữ Nôm hiện có') }} - Việt Nôm{% endblock %}

{% block page_content %}
<div class="col-md-8 col-md-offset-2">
    {% for nom in noms %}
    <a href="{{ url_for('.nom_view', id=nom.id) }}">
        <button class="btn btn-default btn-lg nom-index">{{ nom.character }}</button>
    </a>
    {% endfor %}
    {% if pagination %}
    <div class="text-center">
        {{ macros.pagination_widget(pagination, '.nom_index') }}
    </div>
    {% endif %}
</div>
{% endblock %}

app/templates/main/nom_view.html
{% extends "base.html" %}
{% import "_macros.html" as macros %}
{% block title %}{{ nom.character }}  "{{ my_post.keyword if my_post.keyword else nom.keyword }}"
- Việt Nôm
{% endblock %}

{% block page_content %}
<div class="col-md-3">
    <div id="kanjiViewer text-center">
        <div id="sample-btn">
            <nav>
            <ul class="pager">
                <li class="previous">
                    <a href="{{ nom.id - 1 if nom.id > 1 else nom.count }}">
                        <span aria-hidden="true">{{ _('Trước') }}</span></a>
                </li>
                <li id="replay">
                    <a href="#replay"><span class="glyphicon glyphicon-repeat" aria-hidden="true"></span></a>
                </li>
                <li class="next"><a href="{{ nom.id + 1 if nom.id < nom.count else 1 }}">
                        <span aria-hidden="true">{{ _('Tiếp') }}</span></a>
                </li>
            </ul>
            </nav>
        </div>
        <div id="draw"></div>
    </div>
    <div id="search-box">
        <div class="input-group">
        <input id="search-query" type="search" class="form-control input-sm" 
        placeholder="{{ _('Tìm theo từ khóa...') }}">
        <span class="input-group-btn">
            <button class="btn btn-default btn-sm" type="button" id="clear">{{ _('Xóa')}}</button>
        </span>
        </div>
        <div id="search-results" style="display: none;">
            <div class="entries"></div>
        </div>
    </div>
</div>

<div class="col-md-7">
    <div class="page-header">
        <h2>{{ my_post.keyword if my_post.keyword else nom.keyword }}
            <span class="pull-right"><a href="{{ url_for('.edit_post', id=nom.id) }}">
                    <button class="btn btn-success">{{ _('Chỉnh sửa') }}</button></a>
            </span>
            {% if current_user.is_administrator() %}
            <small>
                <a href="{{ url_for('admin.edit_nom', id=nom.id) }}">
                    <span class="glyphicon glyphicon-link" aria-hidden="true"></span>
                </a>
            </small>
            {% endif %}
        </h2>
    </div>
    <div class="well post-body">
        {% if my_post.story_html %}
            {{ my_post.story_html | safe }}
        {% else %}
            {{ my_post.story }}
        {% endif %}
    </div>
    <div class="panel panel-success">
        <div class="panel-body post-body"><h4>{{ nom.character}}
                &nbsp;
                <small>{{ nom.meaning }}
                &nbsp;
                <a href="http://nomfoundation.org/common/vnom_details.php?codepoint={{ nom.ucn_code }}"
                    target="_blank">
                <span class="glyphicon glyphicon-new-window" aria-hidden="true"></span></a>
                </small>
            </h4>
        </div>
    </div>
    <div class="posts">
        {% include '_posts.html' %}
    </div>
    <div class="pagination">
        {% if pagination %}
            {{ macros.pagination_widget(pagination, '.nom_view', id=nom.id) }}
        {% endif %}
    </div>
</div>
{% endblock %}

{% block scripts %}
{{ super() }}
  <script type="text/javascript" src="{{ url_for('static', filename='js/dmak.js') }}"></script>
  <script type="text/javascript" src="{{ url_for('static', filename='js/raphael-min.js') }}"></script>
  <script>
    var dmak = new Dmak('{{ nom.character }}', {'element': "draw"});
    var g = document.getElementById("replay");
    g.onclick = function () {
      dmak.erase();
      setTimeout(function () {
          dmak.render()}, 1500);
    };
  </script>


  <script type="text/javascript" src="{{ url_for('static', filename='js/lunr.min.js') }}"></script>
  <script type="text/javascript" src="{{ url_for('static', filename='js/app.js') }}"></script>
  <script type="text/javascript" src="{{ url_for('static', filename='js/search.js') }}"></script>

{% endblock %}

app/templates/main/user.html
{% extends "base.html" %}
{% import "_macros.html" as macros %}
{% block title %}{{ user.username }} - Việt Nôm{% endblock %}

{% block page_content %}
<div class="col-md-3">
    <img class="img-rounded profile-thumbnail" src="{{ user.gravatar(size=230) }}">
    <h1>{{ user.username }}</h1>

    {% if user.name %}
    <p>
    <span class="glyphicon glyphicon-user" aria-hidden="true"></span>
    {{ user.name }}
    </p>
    {% endif %}

    {% if user.location %}
    <p>
    <span class="glyphicon glyphicon-map-marker" aria-hidden="true"></span>
    {{ user.location }}
    </p>
    {% endif %}

    {% if current_user.is_administrator() %}
    <p>
    <span class="glyphicon glyphicon-envelope" aria-hidden="true"></span>
    <a href="mailto:{{ user.email }}">{{ user.email }}</a></p>
    {% endif %}

    {% if user.url %}
    <p>
        <span class="glyphicon glyphicon-link" aria-hidden="true"></span>
        <a href="{{ user.url }}">{{ user.url }}</a>
    </p>
    {% endif %}

    <p>
        <span class="glyphicon glyphicon-bookmark" aria-hidden="true"></span>
        {{ _('Thành viên từ') }} {{ moment(user.member_since).format('DD/MM/YYYY') }}
    </p>

    {% if current_user.is_administrator() %}
    <p>
    <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
        <a href="{{ url_for('admin.edit_profile', id=user.id) }}">
            {{ _('Sửa hồ sơ') }}
        </a>
    </p>
    {% endif %}
</div>

<div class="col-md-7">
    <ul class="nav nav-tabs">
        <li role="presentation" class="active">
            <a href="#share">
                {{ _('Chia sẻ') }}</a>
        </li>
    </ul>
    {% include '_stories.html' %}
    <div class="pagination">
        {% if pagination %}
            {{ macros.pagination_widget(pagination, '.user', username=user.username) }}
        {% endif %}
    </div>
</div>
{% endblock %}